### ISSUE TITLE
FoleySynth

### ISSUE THREAD

**Issue by Werner88** [ffAudio/PluginGuiMagic#18]
Hi Daniel, thank you for the example Synth, as always a lecture in programming modern c++:)

To get rid of the random "portamento", a little improvement could be to change
```
void FoleysSynth::FoleysVoice::updateFrequency (BaseOscillator& oscillator)
{
    const auto freq = getFrequencyForNote (getCurrentlyPlayingNote(),
                                           pitchWheelValue * maxPitchWheelSemitones
                                           + oscillator.detune->get());
    oscillator.osc.get<0>().setFrequency (freq * oscillator.multiplier);
}
```

into

```
void FoleysSynth::FoleysVoice::updateFrequency (BaseOscillator& oscillator, bool force)
{
    const auto freq = getFrequencyForNote (getCurrentlyPlayingNote(),
                                           pitchWheelValue * maxPitchWheelSemitones
                                           + oscillator.detune->get());
    oscillator.osc.get<0>().setFrequency (freq * oscillator.multiplier, force);
}
```

plus defining a bool named e.g. firstRun, it should be set to true on startNote,
then in renderNextBlock passed to updateFrequency (*osc, firstRun);
And at the end of renderNextBlock set to false.

This way the osc's currentFrequency (=startFrequency) equals it's targetFrequency when it is startet after NoteOn.

**Comment by ffAudio** [comment]
Thanks @Werner88, indeed I missed the fact that the frequency is smoothed in the oscillator.
I fixed it slightly differently, see the commit above.
This will be merged to master with the next regular release.
