### ISSUE TITLE
Licensing seems contradictory.

### ISSUE THREAD

**Issue by shayneoneill** [ffAudio/PluginGuiMagic#19]
I dont understand the license text.

You say its a BSD 3 clause license, which permits commercial use.

Then you say "free for non commercial use", which implies its not free for commercial use. 

It can't be both Which one is it? 

(Also guys, hire a lawyer if you want to be creative with licenses. Your commercializing scheme has likely been torpedoed by this)

**Comment by shayneoneill** [comment]
Ahhh reread it. The language is "should" not "must". The code is open source and thus available for commercial use but the support is whats being sold. Got it.

**Comment by ffAudio** [comment]
Thanks for commenting.
I know, Foleys Finest Audio sounds bold, but it is just myself, so not a huge budget to spend on lawyers. I am a strong believer in sharing and returning favours, hence the rather soft wording, as you noticed.

Having said that, the BSD license as such (and as quoted in the foleys_gui_magic) doesn't specify if the product may be used in commercial software. So it is absolutely legal to offer the code under two different licenses for commercial and non commercial use. I know it is probably not the source a lawyer would quote, but see wikipedia https://en.wikipedia.org/wiki/Multi-licensing
> Multi-licensing is the practice of distributing software under two or more different sets of terms and conditions. This may mean multiple different software licenses or sets of licenses. Prefixes may be used to indicate the number of licenses used, e.g. dual-licensed for software licensed under two different licenses. 

As well as about the BSD license: https://en.wikipedia.org/wiki/BSD_licenses#Commercial_license_compatibility
> The 3-clause BSD license, like most permissive licenses, is compatible with almost all FOSS licenses (and as well proprietary licenses).

In future to sweeten the deal, I am planning to release additional value to license buyers exclusively, like stereo plots, gonio meters, wave plots... but that's just just a plan and depends, if users are happy to buy a license.

**Comment by ffAudio** [comment]
With no further feedback I close this now.

**Comment by shayneoneill** [comment]
Yes, but both licenses permit commercial use. You really need to run this past a lawyer because as it stance someone can use it commercially without paying a licence and be 100% safe in doing so, because the BSD license does NOT forbid it. You need to fix it or your commercialization plans will fail.

To quote the FreeBSD project:
"The so-called new BSD license applied to FreeBSD within the last few years is effectively a statement that you can do anything with the program or its source, but you do not have any warranty and none of the authors has any liability (basically, you cannot sue anybody). This new BSD license is intended to encourage product commercialization. Any BSD code can be sold or included in proprietary products without any restrictions on the availability of your code or your future behavior"

**Comment by ffAudio** [comment]
Thanks for your insight, much appreciated.
