### ISSUE TITLE
Workaround for passing AudioProcessor in new factory pattern

### ISSUE THREAD

**Issue by maxgraf96** [ffAudio/PluginGuiMagic#21]
Hi!

I'm really enjoying working with the library. However, I'm struggling with the current update, as it took away support for passing the AudioProcessor to GUI factories. I wanted to ask if there is a possible workaround for this at the current point, since I feel like this is a rather big breaking change to the data flow of the system.

Best,
Max

**Comment by ffAudio** [comment]
Hi Max,

thanks for using the PluginGuiMagic. I know, I wasn't happy removing that function, but the templating approach was quite limiting.
What you can do is to downcast the processor reference to your specific processor. I will add that to the ExtendingExample to explain it. Actually I add now a `AudioProcessor* getProcessor()` to MagicGuiState, it will be available in the 1.2.1 update arriving soon, just checking on the CI.

Let me know if that works for you.
Cheers,
Daniel

**Comment by ffAudio** [comment]
This change with 1.2.1 is now live.

**Comment by maxgraf96** [comment]
Oh sweet, that works perfectly! Thank you for the quick response :)
Max
