### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by kritzikratzi** [ffAudio/PluginGuiMagic#25]
i'm pretty sure this type of licensing is dubious. you can't really claim you give out code under bsd-3 clause _only_ for non-commercial. the bsd-3 clause allows commercial use. so either you do allow commercial use, or you don't supply code under the 3-clause bsd. you can't have it both ways. as soon as you apply additional restrictions it's a different license. 

as much pita as gpl-3 dual licensing is, i think that's what you really want. 

of course, people can still buy licenses, but as far as i can tell that's completely optional and you can't sue anyone who doesn't. 

not a lawyer, so i'm curious if you thought this through.

**Comment by ffAudio** [comment]
Thank you for your concern. Yes, this view was pointed to me before. However there are a few sources that say otherwise:

> "Is BSD-3 compatible with dual licensing?" - "The answer to the first question is clearly yes. You own the copyright and can issue copies of your work under different licenses. [...]"
https://softwareengineering.stackexchange.com/questions/339623/is-bsd-3-compatible-with-dual-licensing

And also Wikipedia states:
> "The FreeBSD project argues on the advantages of BSD-style licenses for companies and commercial use-cases due to their license compatibility with proprietary licenses and general flexibility, stating that the BSD-style licenses place only "minimal restrictions on future behavior" and aren't "legal time-bombs", unlike copyleft licenses."
https://en.wikipedia.org/wiki/BSD_licenses#Commercial_license_compatibility

However, I am not a lawyer, so if you are unsure and want to use it in commercial products without buying a license, you should consult with your lawyer and proceed as you see fit.

**Comment by kritzikratzi** [comment]
dual licensing is never a problem. as the owner of a source, you can dual license as much as you want. i'm saying the problem arises because you're publishing under "bsd, but only for non-commercial use". 

the two sentences after your wiki quote are this: 

    The BSD License allows proprietary use and allows the software released 
    under the license to be incorporated into proprietary products. Works based 
    on the material may be released under a proprietary license as closed 
    source software, allowing usual commercial usages under them. 

i have no direct use for your library, just came across it randomly... so no worries there ^^

**Comment by kritzikratzi** [comment]
ps. closing this, just wanted to make sure you're aware :)

**Comment by ffAudio** [comment]
Thank you, it's much appreciated. If you have ideas how I can improve that I am all ears.
I am aware that it is almost impossible to enforce it anyway and I don't want to punish my users with tracking and copy protection code. I trust my users to support me.

Cheers!
