### ISSUE TITLE
MessageBoxIconType: is not a member of 'juce'

### ISSUE THREAD

**Issue by r00tk1ll** [ffAudio/PluginGuiMagic#31]
I have run into this issue when trying to compile the SignalGenerator Example using MS VS 2019 and the latest Juce framework. 

I'm sure I'm doing something wrong, could you point me in the right direction?

`1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include\memory(2698,56): warning C4244: 'argument': conversion from '_Ty' to 'float', possible loss of data
1>        with
1>        [
1>            _Ty=int
1>        ] (compiling source file ..\..\Source\PluginProcessor.cpp)
1>C:\Users\r00tk1ll\Music\Plugin Development\SignalGenerator\Source\PluginProcessor.cpp(55): message : see reference to function template instantiation 'std::unique_ptr<juce::AudioParameterFloat,std::default_delete<juce::AudioParameterFloat>> std::make_unique<juce::AudioParameterFloat,juce::String&,const char(&)[10],juce::NormalisableRange<float>&,int,0>(juce::String &,const char (&)[10],juce::NormalisableRange<float> &,int &&)' being compiled
1>C:\Users\r00tk1ll\Music\Plugin Development\Juce Modules\foleys_gui_magic\Editor\foleys_PropertiesEditor.cpp(181,65): error C2039: 'MessageBoxIconType': is not a member of 'juce' (compiling source file ..\..\JuceLibraryCode\include_foleys_gui_magic.cpp)
1>C:\JUCE\modules\juce_opengl\utils\juce_OpenGLAppComponent.h(26): message : see declaration of 'juce' (compiling source file ..\..\JuceLibraryCode\include_foleys_gui_magic.cpp)
1>C:\Users\r00tk1ll\Music\Plugin Development\Juce Modules\foleys_gui_magic\Editor\foleys_PropertiesEditor.cpp(181,65): error C3083: 'MessageBoxIconType': the symbol to the left of a '::' must be a type (compiling source file ..\..\JuceLibraryCode\include_foleys_gui_magic.cpp)
1>C:\Users\r00tk1ll\Music\Plugin Development\Juce Modules\foleys_gui_magic\Editor\foleys_PropertiesEditor.cpp(181,85): error C2039: 'QuestionIcon': is not a member of 'juce' (compiling source file ..\..\JuceLibraryCode\include_foleys_gui_magic.cpp)
1>C:\JUCE\modules\juce_opengl\utils\juce_OpenGLAppComponent.h(26): message : see declaration of 'juce' (compiling source file ..\..\JuceLibraryCode\include_foleys_gui_magic.cpp)
1>C:\Users\r00tk1ll\Music\Plugin Development\Juce Modules\foleys_gui_magic\Editor\foleys_PropertiesEditor.cpp(181,97): error C2065: 'QuestionIcon': undeclared identifier (compiling source file ..\..\JuceLibraryCode\include_foleys_gui_magic.cpp)
1>include_juce_audio_plugin_client_utils.cpp`

**Comment by ffAudio** [comment]
Thanks for the message and my apologies. A misconfiguration on my end fooled me that this change was necessary.
The AlertWindow::IconType was moved to juce::MessageBoxIconType, but in fact there is an alias to keep the old method working, which I missed.

The three options to fix it:
- I reverted it already on my develop branch, so it should work with juce's develop and master branch
- The foleys_gui_magic module should already work with juce's latest develop branch
- manually patch the juce::MessageBoxIconType to juce::AlertWindow::IconType

I try to do a release soon when the fixed develop branch will be merged to the main branch, so you can use the stable branch again.

Please let me know if that solves your issues and sorry for any inconvenience.

**Comment by r00tk1ll** [comment]
Awesome! Thanks for the quick reply, I will try it with your latest development branch and let you know. Thanks again!

**Comment by r00tk1ll** [comment]
Okay this is the result of trying with the latest develop branch and Debug x64 Local Windows Debugger on VS 2019

```
JUCE Assertion failure in juce_File.cpp:152
MetalAmp.exe has triggered a breakpoint.
```

And the CallStack

```
MetalAmp.exe!juce::File::parseAbsolutePath(const juce::String & p) Line 152
	at C:\JUCE\modules\juce_core\files\juce_File.cpp(152)
MetalAmp.exe!juce::File::File(const juce::String & fullPathName) Line 29
	at C:\JUCE\modules\juce_core\files\juce_File.cpp(29)
MetalAmp.exe!juce::File::getChildFile(juce::StringRef relativePath) Line 468
	at C:\JUCE\modules\juce_core\files\juce_File.cpp(468)
MetalAmp.exe!juce::File::getNonexistentChildFile(const juce::String & suggestedPrefix, const juce::String & suffix, bool putNumbersInBrackets) Line 607
	at C:\JUCE\modules\juce_core\files\juce_File.cpp(607)
MetalAmp.exe!foleys::ToolBox::setLastLocation(juce::File file) Line 388
	at C:\Users\r00tk1ll\Music\Plugin Development\Juce Modules\foleys_gui_magic\Editor\foleys_ToolBox.cpp(388)
MetalAmp.exe!foleys::MagicGUIBuilder::attachToolboxToWindow::__l2::<lambda>() Line 441
	at C:\Users\r00tk1ll\Music\Plugin Development\Juce Modules\foleys_gui_magic\General\foleys_MagicGUIBuilder.cpp(441)
[External Code]
MetalAmp.exe!`juce::MessageManager::callAsync'::`2'::AsyncCallInvoker::messageCallback() Line 192
	at C:\JUCE\modules\juce_events\messages\juce_MessageManager.cpp(192)
MetalAmp.exe!juce::InternalMessageQueue::dispatchMessage(juce::MessageManager::MessageBase * message) Line 202
	at C:\JUCE\modules\juce_events\native\juce_win32_Messaging.cpp(202)
MetalAmp.exe!juce::InternalMessageQueue::dispatchMessages() Line 240
	at C:\JUCE\modules\juce_events\native\juce_win32_Messaging.cpp(240)
MetalAmp.exe!juce::InternalMessageQueue::dispatchNextMessage(bool returnIfNoPendingMessages) Line 125
	at C:\JUCE\modules\juce_events\native\juce_win32_Messaging.cpp(125)
MetalAmp.exe!juce::MessageManager::dispatchNextMessageOnSystemQueue(bool returnIfNoPendingMessages) Line 266
	at C:\JUCE\modules\juce_events\native\juce_win32_Messaging.cpp(266)
MetalAmp.exe!juce::MessageManager::runDispatchLoop() Line 128
	at C:\JUCE\modules\juce_events\messages\juce_MessageManager.cpp(128)
MetalAmp.exe!juce::JUCEApplicationBase::main() Line 266
	at C:\JUCE\modules\juce_events\messages\juce_ApplicationBase.cpp(266)
MetalAmp.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 47
	at C:\JUCE\modules\juce_audio_plugin_client\juce_audio_plugin_client_Standalone.cpp(47)
[External Code]
```

**Comment by ffAudio** [comment]
That's strange. This is from the new auto save feature. It was supposed to work as opt-in, maybe I should check again if it works without.
It is usually used by adding this line in your processors constructor:
```
FOLEYS_SET_SOURCE_PATH(__FILE__);
```
This will allow the editor to locate your Source folder, create an auto save file there and when you hit save it will already show the correct folder.

Hope that helps

**Comment by r00tk1ll** [comment]
Awesome! That fixed it, I noticed it was in the documentation so it's my fault for overlooking that point. Anyways, everything is working now!

**Comment by ffAudio** [comment]
Awesome. Like I said I thought it would work without and I will add a check for the future.
Cheers
